# Generated by Django 5.1.2 on 2026-03-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('tank_capacity', models.FloatField()),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'DIESEL'), ('GASOLINE', 'GASOLINE')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'fuel_vehicles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FuelRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.IntegerField()),
                ('liters', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('FUELED', 'FUELED')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id', models.IntegerField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by_id', models.IntegerField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fueled_at', models.DateTimeField(blank=True, null=True)),
                ('fueled_by_id', models.IntegerField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.vehiclemodel')),
            ],
            options={
                'db_table': 'fuel_requests_v1',
                'ordering': ['-id'],
            },
        ),
    ]
