# Generated by Django 5.1.2 on 2026-03-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator'), ('USER', 'Standard User')], default='USER', max_length=20),
        ),
    ]
