# Generated by Django 5.1.2 on 2026-03-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkFuelRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_requests_v2',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BulkFuelRequestItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('processed_by_id', models.IntegerField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.vehiclemodel')),
                ('parent_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fuelv2.bulkfuelrequestmodel')),
            ],
            options={
                'db_table': 'fuel_request_items_v2',
                'ordering': ['-id'],
            },
        ),
    ]
