# Generated by Django 5.1.2 on 2026-03-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField()),
                ('status_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shared_idempotency_keys',
                'indexes': [models.Index(fields=['key', 'created_at'], name='shared_idem_key_ac2a72_idx')],
            },
        ),
    ]
